#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     LiftTouchHigh,  sensorTouch)
#pragma config(Sensor, S3,     LiftTouchLow,   sensorTouch)
#pragma config(Sensor, S4,     ArmTouch,       sensorTouch)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     BackLeft,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     FrontLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Lift,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     Arm,           tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     FrontRight,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     BackRight,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    Scoop,                tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "DriveFunctions.h"

void initializeRobot()
{
	const byte max = 127;
	//Lift raises at max speed until top button is pressed.
	while (SensorValue(LiftTouchHigh) != true)
	{
		motor[Lift] = max;
	}
	//Reset Lift encoder. UNCOMMENT IF LIFT ENCODER IS WIRED.
	nMotorEncoder[Lift] = 0;
	//Move Lift down to center.
	bump(Lift, false);

	//Arm retracts at max speed until button is pressed.
	while (SensorValue(ArmTouch) != true)
	{
		motor[Arm] = -max;
	}
	//Reset Arm encoder. UNCOMMENT IF ARM ENCODER IS WIRED.
	//nMotorEncoder[Arm] = 0;
	//Bump arm in for 10ms.
	bump(Arm, true);

	//Reset all drive encoders. UNCOMMENT IF DRIVER ENCODERS ARE WIRED.
	//resetDriveEncoders();
	//Set Scoop to full down position.
	servo[Scoop] = 255;
}

task main()
{

	waitForStart();

	initializeRobot();

}
